flowchart TB
    A["总体架构蓝图"]
    B["需求分析与建设内容"]
    C["设计原则"]
    D["通用质量特性设计总述"]
    E["测试性设计"]
    F["质量控制与风险管理"]
    G["编写目的"]
    H["数据库设计总述"]
    I["数据库表设计"]
    J["质量控制总述"]
    A --> B
    A --> C
    A --> D
    A --> E
    A --> F
    A --> G
    A --> H
    A --> I
    A --> J
