flowchart TB
    A["数据流与接口关系图"]
    B["编写目的"]
    C["功能设计总述"]
    D["功能设计章节"]
    E["核心业务数据设计"]
    F["关键技术"]
    G["建设内容"]
    H["数据库设计总述"]
    I["数据库表设计"]
    J["质量控制总述"]
    A --> B
    A --> C
    A --> D
    A --> E
    A --> F
    A --> G
    A --> H
    A --> I
    A --> J
