flowchart TB
    A["部署与运行支撑图"]
    B["性能设计章节"]
    C["编写目的"]
    D["总体架构设计"]
    E["总体架构图"]
    F["架构图说明"]
    G["部署架构设计"]
    H["功能设计总述"]
    I["功能设计章节"]
    J["环境适应性设计"]
    A --> B
    A --> C
    A --> D
    A --> E
    A --> F
    A --> G
    A --> H
    A --> I
    A --> J
