flowchart TB
    A["部署与运行支撑图"]
    B["性能设计章节"]
    C["编写目的"]
    D["设计原则"]
    E["通用质量特性设计总述"]
    F["测试性设计"]
    G["质量控制与风险管理"]
    H["建设内容"]
    I["数据库设计总述"]
    J["数据库表设计"]
    A --> B
    A --> C
    A --> D
    A --> E
    A --> F
    A --> G
    A --> H
    A --> I
    A --> J
